name = "KSV Orders Sheet Manager DRM"
client_id = "497781ec8fd2691747d174ff4dccde05"
handle = "ksv-orders-sheet-manager-drm"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
extension_directories = ["extensions/"]

[access_scopes]
scopes = "read_orders,write_orders,read_customers"
optional_scopes = ["read_all_orders"]

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = ["https://shopify.dev/apps/default-app-home/api/auth"]

[build]
automatically_update_urls_on_dev = true
